default: distclean report

distclean: clean
	rm -f report.pdf;

clean:
	rm -f report.{aux,bbl,blg,glo,gls,ilg,lof,log,lot,out,synctex.gz,toc};

report:
	pdflatex report;
	pdflatex report;
	pdflatex report;
